name: docker-pipeline
on:
 push:
     paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'sample/'
      - 'CONTRIBUTING.md'

jobs:
  docker-pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: build image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/hello-pipeline-python:v1 .
      - name: verify image
        run: docker images
      - name: Create Container
        run: docker run --name app -itd -p 8080:8080 ${{ vars.DOCKERHUB_USERNAME }}/hello-pipeline-python:v1
      - name: verify container
        run: docker ps
      - name: sleep
        run: sleep 20
      - name: print output
        run: curl http://localhost:8080
      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/hello-pipeline-python:v1 
      - name: cleanup
        run: docker rm -f app

